language: ruby

sudo: false
cache: bundler

before_install:
  - travis_retry gem install bundler

rvm:
  - 2.4.2
  - 2.3.5
  - 2.2.8

env:
  - RAILS=4-2-stable AREL=6-0-stable DB=sqlite
  - RAILS=4-2-stable AREL=6-0-stable DB=mysql
  - RAILS=4-2-stable AREL=6-0-stable DB=postgres
  - RAILS=5-0-stable AREL=7-0-stable DB=sqlite
  - RAILS=5-0-stable AREL=7-0-stable DB=mysql
  - RAILS=5-0-stable AREL=7-0-stable DB=postgres
  - RAILS=5-1-stable AREL=8-0-stable DB=sqlite
  - RAILS=5-1-stable AREL=8-0-stable DB=mysql
  - RAILS=5-1-stable AREL=8-0-stable DB=postgres

matrix:
  include:
    - rvm: 2.4.2
      env: RAILS=master DB=sqlite3
    - rvm: 2.4.2
      env: RAILS=master DB=mysql
    - rvm: 2.4.2
      env: RAILS=master DB=postgres

    - rvm: 2.3.5
      env: RAILS=master DB=sqlite3
    - rvm: 2.3.5
      env: RAILS=master DB=mysql
    - rvm: 2.3.5
      env: RAILS=master DB=postgres

    - rvm: 2.2.8
      env: RAILS=master DB=sqlite3
    - rvm: 2.2.8
      env: RAILS=master DB=mysql
    - rvm: 2.2.8
      env: RAILS=master DB=postgres

before_script:
  - mysql -e 'create database ransack collate utf8_general_ci;'
  - mysql -e 'use ransack;show variables like "%character%";show variables like "%collation%";'
  - psql -c 'create database ransack;' -U postgres
